# Generated by Django 5.2.16 on 2026-07-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_common_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=10),
        ),
    ]
